loki:
  image:
    registry: k3d-registry.localhost:5001
    repository: grafana/loki
    tag: 2.6.1

promtail:
  image:
    registry: k3d-registry.localhost:5001
    repository: grafana/promtail
    tag: 3.5.1
  config:
    snippets:
      extraRelabelConfigs:
        - source_labels: [__meta_kubernetes_namespace]
          action: keep
          regex: (agentic-edge-stack|monitoring)
  initContainer:
    - name: init
      image: k3d-registry.localhost:5001/docker.io/busybox:1.33
      imagePullPolicy: IfNotPresent
      command:
        - sh
        - -c
        - sysctl -w fs.inotify.max_user_instances=512
      securityContext:
        privileged: true

grafana:
  sidecar:
    datasources:
      enabled: false
