prometheusOperator:
  image:
    repository: prometheus-operator/prometheus-operator
    tag: v0.91.0
  prometheusConfigReloader:
    image:
      repository: prometheus-operator/prometheus-config-reloader
      tag: v0.91.0

prometheus:
  prometheusSpec:
    image:
      repository: prometheus/prometheus
      tag: v3.12.0-distroless
    # Make sure Prometheus Operator discovers our ServiceMonitor / PodMonitor without filtering namespace
    podMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false

alertmanager:
  alertmanagerSpec:
    image:
      repository: prometheus/alertmanager
      tag: v0.32.2

nodeExporter:
  image:
    repository: prometheus/node-exporter
    tag: v1.11.1-distroless

kube-state-metrics:
  image:
    repository: kube-state-metrics/kube-state-metrics
    tag: v2.19.0

grafana:
  image:
    repository: grafana/grafana
    tag: 13.0.1-security-01
  sidecar:
    image:
      repository: kiwigrid/k8s-sidecar
      tag: "2.7.3"
  service:
    type: NodePort
    nodePort: 30030
  additionalDataSources:
    - name: Loki
      type: loki
      uid: loki
      access: proxy
      url: http://loki-stack:3100
      isDefault: false
      jsonData:
        maxLines: 1000

# Disable metric scraping of components not present/accessible in standard local k3s clusters to prevent console errors
kubeControllerManager:
  enabled: false
kubeScheduler:
  enabled: false
kubeEtcd:
  enabled: false
kubeProxy:
  enabled: false
