import json
import logging
from fastapi import FastAPI, HTTPException, Header, Depends
from fastapi.responses import StreamingResponse
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from prometheus_fastapi_instrumentator import Instrumentator

from app.config import settings
from app.agent import run_agent_stream

# Setup logging configuration
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s"
)
logger = logging.getLogger("app.main")

# Initialize FastAPI application
app = FastAPI(
    title="Agentic Edge Stack - AI Agent Service",
    description="Primary backend microservice orchestrating LLM tool-calling and vector search.",
    version="1.0.0"
)

# Enable CORS for frontend flexibility
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Initialize Prometheus Metrics Instrumentator (Track B)
Instrumentator().instrument(app).expose(app)

class ChatRequest(BaseModel):
    message: str

def verify_api_key(authorization: str = Header(default=None)):
    """
    Optional API Key verification layer.
    """
    if not authorization:
        # Default dev mode bypass to ensure local ease of testing
        return
    
    parts = authorization.split()
    if len(parts) == 2 and parts[0].lower() == "bearer":
        token = parts[1]
        if token != settings.api_key:
            raise HTTPException(status_code=401, detail="Unauthorized: Invalid API Key")
    else:
        raise HTTPException(status_code=401, detail="Unauthorized: Invalid Authorization Header format")

@app.get("/health", tags=["Lifecycle"])
def health_check():
    """
    Liveness and Readiness probe target.
    """
    return {
        "status": "healthy",
        "llm_url": settings.llm_url,
        "qdrant_url": settings.qdrant_url
    }

@app.post("/chat", tags=["Agent"])
async def chat_endpoint(request: ChatRequest, authorization: str = Header(default=None)):
    """
    Server-Sent Events (SSE) streaming /chat endpoint.
    Streams back tokens generated by the LLM Agent.
    """
    # Verify API key if configured
    verify_api_key(authorization)
    
    logger.info(f"Received chat request: {request.message[:100]}")

    async def sse_generator():
        try:
            async for token in run_agent_stream(request.message):
                # Standard SSE format: "data: <payload>\n\n"
                payload = json.dumps({"token": token})
                yield f"data: {payload}\n\n"
            
            # Send standard closing token
            yield "data: [DONE]\n\n"
        except Exception as e:
            logger.exception("Error in SSE generator stream:")
            err_payload = json.dumps({"error": str(e)})
            yield f"data: {err_payload}\n\n"

    return StreamingResponse(
        sse_generator(),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "Connection": "keep-alive",
            "X-Accel-Buffering": "no"  # Disable buffering for Nginx/ingress proxies
        }
    )

@app.get("/")
def read_root():
    return {
        "message": "Welcome to the Agentic Edge Stack AI Agent Service. Access endpoints at /docs, metrics at /metrics, and health at /health."
    }
