{{- if .Values.qdrant.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qdrant-storage-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - {{ .Values.qdrant.persistence.accessMode }}
  storageClassName: {{ .Values.qdrant.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.qdrant.persistence.size }}
{{- end }}
